name:                bottomTsh-untyped
version:             0.1.0.0
license:             BSD3
author:              "Joachim Tilsted Kristensen."
maintainer:          "tilsted@di.ku.dk"
copyright:           "2019 Joachim Tilsted Kristensen"

dependencies:
- base >= 4.7 && < 5
- parsec
- csound-expression
- csound-expression-typed
- csound-sampler
- singletons
- mtl
- first-class-families
- typenums
- tuple
- parsec
- syb
- template-haskell

library:
  source-dirs: src

# executables:
#   dseq-untyped-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - dseq-untyped

tests:
  dseq-untyped-test:
    main:                All.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dseq-untyped
    - HUnit
